apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
    argocd.argoproj.io/ignore-healthcheck: "true"
spec:
  replicas: 1
  revisionHistoryLimit: 3
  dummy: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2-non-existant
        name: guestbook-ui
        ports:
        - containerPort: 80
